# mandatory config
task: evaluation
# similarity list for stream process
similarity_file: /home/zhongwei/Data_integration/er_embedding_streaming/pipeline/similarity/fodors_zagats.graphml
# ground truth file
match_file: /home/zhongwei/Data_integration/data/datasets/dataset2-fordors/matches-fodors_zagats.txt
source_a: 533
# optional config
output_file_name: fodors_zagats